"""§11.3 CodeOptimizer — entry point for code optimization.

Corresponds to PLANNING_AND_RL.md §11.3.

Usage:
    from optagent.v2.domains.code import CodeOptimizer

    opt = CodeOptimizer(
        source_path=Path("./my_module.py"),
        backend=OpenCodeBackend(),
    )
    result = opt.optimize(
        objective="minimize latency",
        max_rounds=5,
    )
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

from optagent.v2.state import Observation
from optagent.v2.planner import DefaultPlanner
from optagent.v2.mcts import MCTSOptimizer
from optagent.v2.hybrid import HybridOptimizer
from optagent.v2.domains.code.state import CodeState, CodeArtifact
from optagent.v2.domains.code.action import EditCode, RunTests, RunBenchmark
from optagent.v2.domains.code.proposer import CodeProposer
from optagent.v2.domains.code.executor import CodeExecutor
from optagent.v2.domains.code.reward import create_code_reward_spec


class CodeOptimizer:
    """End-to-end code optimization using v2 framework."""

    def __init__(
        self,
        source_path: Path,
        backend: Any = None,
        work_dir: Optional[Path] = None,
    ):
        self.source_path = Path(source_path)
        self.backend = backend
        self.executor = CodeExecutor(work_dir=work_dir)
        self.proposer = CodeProposer(backend=backend)
        self.reward_spec = create_code_reward_spec()

    def optimize(self, objective: str, max_rounds: int = 5) -> CodeState:
        """Run optimization loop with test, benchmark, and write-back.

        Args:
            objective: natural language objective (e.g., "minimize latency")
            max_rounds: maximum optimization rounds

        Returns:
            final CodeState with best incumbent
        """
        # Read initial code
        initial_code = self.source_path.read_text()
        current_code = initial_code
        best_code = initial_code
        best_latency = float("inf")

        # Build initial state
        code = CodeArtifact(
            artifact_id="initial",
            source_path=self.source_path,
            content=initial_code,
        )
        state = CodeState(
            requirement={"objective": objective, "source": str(self.source_path)},
            code=code,
        )

        # Baseline benchmark
        print("[Baseline] Running benchmark on original code...")
        baseline_result = self._benchmark_code(initial_code, state)
        baseline_latency = baseline_result.get("latency_ms", float("inf"))
        print(f"[Baseline] Latency: {baseline_latency:.3f} ms")

        # Set up MCTS with minimal simulations for real backend
        mcts = MCTSOptimizer(objectives=self.reward_spec.objectives)

        # Optimization loop
        v2_state = state.to_v2_state()
        for round_idx in range(max_rounds):
            print(f"\n[Round {round_idx + 1}/{max_rounds}] Generating optimization...")
            # Search for best action (minimal simulations to avoid repeated LLM calls)
            action = mcts.search(v2_state, self.proposer, n_simulations=1, max_depth=3)
            if action is None:
                print(f"[Round {round_idx + 1}] No action found")
                break

            # Only handle EditCode actions (generated by LLM)
            if not isinstance(action, EditCode):
                continue

            # Set target path
            if action.target_path == Path("."):
                action.target_path = self.source_path

            # Apply optimization
            result = self.executor.apply_diff(state, action)
            if not result["success"]:
                print(f"[Round {round_idx + 1}] Diff failed: {result.get('error', '')[:100]}")
                continue

            candidate_code = result["patched_content"]
            print(f"[Round {round_idx + 1}] Diff applied, code length: {len(candidate_code)}")

            # Run tests on optimized code
            print(f"[Round {round_idx + 1}] Running tests...")
            test_result = self._run_tests_on_code(candidate_code, state)
            if not test_result.get("passed", False):
                print(f"[Round {round_idx + 1}] Tests FAILED, skipping")
                print(f"[Round {round_idx + 1}] Test output: {test_result.get('output', '')[:500]}")
                continue
            print(f"[Round {round_idx + 1}] Tests PASSED ({test_result.get('test_count', 0)} tests)")

            # Run benchmark on optimized code
            print(f"[Round {round_idx + 1}] Running benchmark...")
            bench_result = self._benchmark_code(candidate_code, state)
            candidate_latency = bench_result.get("latency_ms", float("inf"))
            print(f"[Round {round_idx + 1}] Latency: {candidate_latency:.3f} ms (baseline: {baseline_latency:.3f} ms)")

            # Update state with results
            state.code.content = candidate_code
            state.code.test_results = test_result
            state.code.benchmark_results = bench_result
            v2_state = state.to_v2_state()

            # Keep best
            if candidate_latency < best_latency:
                best_code = candidate_code
                best_latency = candidate_latency
                print(f"[Round {round_idx + 1}] NEW BEST! Speedup: {baseline_latency / candidate_latency:.2f}x")
            else:
                print(f"[Round {round_idx + 1}] Not better than current best")

        # Write back best code to source file
        if best_code != initial_code:
            print(f"\n[Write-back] Saving optimized code to {self.source_path}")
            self.source_path.write_text(best_code)
            print(f"[Write-back] Done. Best latency: {best_latency:.3f} ms (baseline: {baseline_latency:.3f} ms, speedup: {baseline_latency / best_latency:.2f}x)")
        else:
            print("\n[Write-back] No improvement found, keeping original code")

        # Return final state with best code
        state.code.content = best_code
        return state

    def _run_tests_on_code(self, code: str, state: CodeState) -> dict:
        """Write code to temp file and run tests."""
        # Create temp copy with candidate code + original tests
        # pytest requires file name to start with 'test_'
        temp_path = self.executor.work_dir / "test_candidate.py"
        # Extract test functions from original code
        original_code = self.source_path.read_text()
        import re
        tests = re.findall(r'(def test_.*?:.*?)(?=\ndef |\Z)', original_code, re.DOTALL)
        full_code = code + "\n\n" + "\n\n".join(tests)
        temp_path.write_text(full_code)
        # Update state to point to temp file for testing
        original_path = state.code.source_path
        state.code.source_path = temp_path
        action = RunTests(test_command="pytest -q --tb=short", target_path=temp_path.parent)
        result = self.executor.run_tests(state, action)
        # Restore original path
        state.code.source_path = original_path
        return result

    def _benchmark_code(self, code: str, state: CodeState) -> dict:
        """Write code to temp file and run benchmark."""
        # Create temp copy with candidate code
        temp_path = self.executor.work_dir / "candidate.py"
        temp_path.write_text(code)
        # Build benchmark command: import and run a micro-benchmark
        bench_script = self.executor.work_dir / "bench_runner.py"
        bench_script.write_text(
            "import timeit\n"
            "import sys\n"
            f"sys.path.insert(0, '{temp_path.parent}')\n"
            "from candidate import slow_sum\n"
            "\n"
            "# Warm-up\n"
            "slow_sum(100)\n"
            "\n"
            "# Benchmark\n"
            "elapsed = timeit.timeit('slow_sum(100000)', globals={'slow_sum': slow_sum}, number=5)\n"
            "print(f'{elapsed * 1000 / 5:.6f} msec per loop')\n"
        )
        # Update state to point to temp file
        original_path = state.code.source_path
        state.code.source_path = temp_path
        action = RunBenchmark(
            benchmark_command=f"python3 {bench_script}",
            iterations=5,
        )
        result = self.executor.run_benchmark(state, action)
        # Restore original path
        state.code.source_path = original_path
        return result
